# Generated by Django 5.2.6 on 2025-09-19 18:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('cedula', models.IntegerField()),
                ('sueldo', models.FloatField()),
                ('departamento', models.CharField()),
                ('cargo', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Nomina',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('aniomes', models.DateField()),
                ('tot_ing', models.FloatField()),
                ('tot_des', models.FloatField()),
                ('neto', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='NominaDetalle',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('sueldo', models.IntegerField()),
                ('bono', models.IntegerField()),
                ('tot_ing', models.IntegerField()),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nomina.empleado')),
                ('nomina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nomina.nomina')),
            ],
        ),
    ]
