# Generated by Django 5.2.6 on 2025-09-20 18:42

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nomina', '0002_nominadetalle_iess_nominadetalle_neto_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empleado',
            name='cedula',
            field=models.CharField(help_text='Cédula ecuatoriana de 10 dígitos', max_length=10, unique=True, validators=[django.core.validators.RegexValidator(message='La cédula debe tener exactamente 10 dígitos numéricos.', regex='^\\d{10}$')]),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='sueldo',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0, 'El sueldo no puede ser negativo.')]),
        ),
    ]
