# Generated by Django 5.2.7 on 2025-10-13 23:30

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nomina', '0003_alter_empleado_cedula_alter_empleado_sueldo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nominadetalle',
            name='bono',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0'), 'El bono no puede ser negativo.')]),
        ),
        migrations.AlterField(
            model_name='nominadetalle',
            name='prestamo',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0'), 'El préstamo no puede ser negativo.')]),
        ),
        migrations.AlterField(
            model_name='nominadetalle',
            name='sueldo',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0'), 'El sueldo no puede ser negativo.')]),
        ),
    ]
